#pragma once
//
//
//
//
//
//
//
//
//
//
//
//
//
// 
// I HAVE IMPLEMENTED A STARTING SCORE SYSTEM THAT BEHAVE AS FOLLOWS:
// U START WITH 10,000 POINTS.
// EVERY 5 SECONDS YOU LOSE 100 POINTS.
// WHEN YOU DIE YOU LOSE 500 POINTS.
// WHEN HITTING A GHOST OR A BARREL YOU GET 1000 POINTS(TODO)
// 
// ALSO IMPLEMENTED A CLOCK THAT PRITNS HOW MUCH TIME PASSED SINCE YOU STARTED PLAYING
// 
// NOTES TO SELF:
// - NEED TO GO THROUGH EVERY FUNCTION AND SEE IF IT NEED CONST OR NAH
// - NEED TO *NOT* USE MAGIC NUMBERS, WILL BE ESIEAR TO CHECK AT THE END, AFTER WORKING WITH FILES 
// - NEED TO IMPLEMENT INHERITEGE
// - AGAIN, NEED TO CLEAN THE MAIN LOOP A LITTLE BIT BECAUSE ITS STARTING TO LOOK MESSY.
// 
// - GAME IS WORKING WELL THO, GHOSTS STILL HAVE THE ISSUE OF ERASING THE PATISH BUT IT WILL BE EASIER TO SOLVE AFTER READING FROM FILES.
// 
// 
// 
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//